# Generated by Django 5.2.9 on 2026-01-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_slug'),
        ('contentmgmt', '0005_alter_folder_parent_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='contentmgmt.mediafile'),
        ),
    ]
